/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/enus/rules/constants.
   The lifted ones are in delta_consts_enus.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t enus_evv_authored_data[] = {
    /* lex_prefix_re, 2 bytes at 0 */
    24,2,
    /* fence_03, 1 bytes at 2 */
    3,
    /* lts_bt, 2 bytes at 3 */
    11,26,
    /* say_04, 1 bytes at 5 */
    4,
    /* say_01, 1 bytes at 6 */
    1,
    /* lts_wr, 2 bytes at 7 */
    28,24,
    /* say_18, 1 bytes at 9 */
    24,
    /* say_1b, 1 bytes at 10 */
    27,
    /* lts_dg, 2 bytes at 11 */
    13,15,
    /* say_11, 1 bytes at 13 */
    17,
    /* lts_dj, 2 bytes at 14 */
    13,17,
    /* lts_mech, 4 bytes at 16 */
    20,2,12,16,
    /* say_141f07, 3 bytes at 20 */
    20,31,7,
    /* lts_mn, 2 bytes at 23 */
    20,21,
    /* say_15, 1 bytes at 25 */
    21,
    /* say_14, 1 bytes at 26 */
    20,
    /* lts_mb, 2 bytes at 27 */
    20,11,
    /* lts_ng, 2 bytes at 29 */
    21,15,
    /* say_16, 1 bytes at 31 */
    22,
    /* lts_then, 4 bytes at 32 */
    26,16,2,21,
    /* lts_ton, 3 bytes at 36 */
    26,4,21,
    /* lts_qu, 2 bytes at 39 */
    23,5,
    /* lts_et, 2 bytes at 41 */
    2,26,
    /* say_07, 1 bytes at 43 */
    7,
    /* lts_e, 1 bytes at 44 */
    2,
    /* say_071b, 2 bytes at 45 */
    7,27,
};

const delta_store enus_delta_authored_store[] = {
    { enus_evv_authored_data, sizeof enus_evv_authored_data },
    { 0, 0 },
};
