/* Generated by tools/delta-emit.py. Do not edit.

   Everything the rules name by address: the language's
   string constants and the compiler's own, as they lie in
   the object each was compiled into.

   A pronunciation changed in lang/jajp/jajp.dict is appended
   here by tools/delta-dict.py, which gives the edited
   action a record of its own rather than writing over the
   one it had, since several actions can name the same
   bytes. Running this lifter again puts IBM's own back
   and loses those edits. */

#include <stdint.h>

#include "delta_rules_jajp.h"

uint8_t jajp_evv_glob_bss_4[6] = {
    0,0,0,0,0,0,
};

uint8_t jajp_evv_glob_data_3[130] = {
    0,1,0,0,0,1,2,3,4,5,6,7,8,9,1,10,
    11,12,0,0,12,12,0,0,128,168,0,0,128,168,129,119,
    128,169,0,0,128,171,0,0,129,119,0,0,129,228,0,0,
    129,229,13,0,130,42,0,0,130,43,14,15,16,17,18,19,
    199,0,0,0,199,72,2,20,202,21,22,23,24,25,26,27,
    28,3,0,0,3,20,30,31,34,35,37,4,4,4,40,42,
    44,45,46,5,5,5,51,52,53,54,55,6,6,6,63,64,
    65,7,70,71,72,73,75,76,8,0,0,0,8,8,81,87,
    88,9,
};

uint8_t jajp_evv_ja_text_data_3[836] = {
    11,3,18,18,5,24,3,20,6,73,18,5,1,26,26,4,
    20,6,73,18,5,0,0,0,46,6,73,22,5,0,0,0,
    13,4,73,24,5,0,0,0,22,6,73,25,2,42,26,4,
    18,1,24,1,73,26,26,4,1,42,13,4,1,25,5,26,
    2,24,3,73,25,5,18,5,18,1,73,18,18,4,0,0,
    18,1,73,18,18,4,72,26,4,73,13,52,3,0,0,0,
    16,1,73,3,14,5,42,0,18,1,25,2,42,0,0,0,
    3,18,9,73,24,5,0,0,22,5,24,1,25,5,0,0,
    11,1,18,18,5,25,5,24,1,73,46,46,5,0,0,0,
    26,1,26,2,11,9,0,0,11,1,18,18,5,18,5,9,
    73,26,4,0,26,3,73,24,5,13,2,0,18,1,73,18,
    18,4,26,4,73,13,52,3,25,2,20,3,18,4,73,24,
    4,42,0,0,18,4,73,24,4,42,0,0,1,22,4,73,
    25,5,26,4,24,4,14,3,18,5,9,73,26,4,0,0,
    18,4,73,42,20,1,0,0,30,4,73,24,3,26,46,8,
    25,1,73,3,13,4,26,26,4,0,0,0,30,4,73,24,
    3,9,73,18,8,0,0,0,25,5,24,1,73,46,46,5,
    16,1,26,2,21,1,20,6,73,18,5,0,3,26,46,3,
    21,3,73,0,25,1,42,0,30,4,73,42,15,4,73,0,
    24,4,18,5,73,0,0,0,21,1,73,21,1,0,0,0,
    16,1,26,46,3,73,0,0,18,30,10,73,31,2,73,24,
    4,0,0,0,7,73,0,0,11,8,73,0,46,8,73,0,
    13,8,73,0,8,73,0,0,2,73,14,5,13,52,8,73,
    2,73,3,26,46,3,0,0,1,73,3,0,13,52,2,73,
    3,0,0,0,18,2,73,3,2,73,24,5,2,73,20,5,
    2,73,21,5,9,73,0,0,22,8,73,0,6,24,5,0,
    2,73,25,5,26,8,73,0,30,10,73,0,11,5,73,3,
    13,1,73,11,5,24,30,10,2,73,18,18,5,25,5,0,
    28,1,73,3,31,2,73,26,26,4,0,0,18,3,15,9,
    2,73,21,30,1,0,0,0,11,7,73,26,1,0,0,0,
    30,10,73,24,4,0,0,0,46,9,24,30,1,18,5,0,
    2,73,25,25,5,0,0,0,9,73,72,7,73,0,0,0,
    18,5,9,73,26,4,26,4,73,13,52,3,11,5,73,24,
    2,26,26,4,13,1,73,46,46,5,0,0,46,9,16,30,
    9,0,0,0,25,1,18,1,25,1,20,1,21,4,72,11,
    3,18,18,5,24,3,20,6,73,18,5,0,25,2,73,42,
    26,4,0,0,22,4,73,42,13,4,0,0,2,73,42,0,
    25,2,73,26,25,5,21,4,72,3,73,42,11,5,42,4,
    73,42,22,5,18,4,22,8,24,1,73,3,26,4,0,0,
    5,2,21,3,73,72,18,1,18,1,73,24,2,26,1,72,
    1,73,3,0,26,9,24,4,18,5,0,0,26,46,9,4,
    73,42,22,5,13,4,0,0,22,5,24,1,25,5,72,20,
    1,3,21,1,25,5,0,0,5,2,21,3,73,72,18,1,
    18,1,73,24,2,26,1,72,21,3,73,0,5,2,21,3,
    73,72,18,1,18,1,73,24,2,26,1,72,25,1,42,0,
    20,30,10,0,11,5,42,25,2,26,25,5,21,4,72,3,
    73,42,0,0,5,2,21,3,73,72,18,1,18,1,73,24,
    2,26,1,72,3,26,46,3,30,4,42,11,5,42,21,4,
    72,3,26,46,3,0,0,0,21,3,11,5,42,21,4,72,
    3,26,46,3,30,4,42,11,5,42,21,4,72,25,1,42,
    25,1,18,1,25,1,20,1,21,4,72,16,1,26,2,21,
    20,6,73,18,5,0,0,0,18,1,18,2,73,24,5,0,
    28,1,24,5,
};

uint8_t jajp_evv_js_cdur_data_3[2] = {
    18,24,
};

uint8_t jajp_evv_jt_phnol_data_3[11] = {
    0,0,0,1,8,21,2,0,8,24,14,
};

uint8_t jajp_evv_jt_spr_bss_15[1] = {
    0,
};

uint8_t jajp_evv_jt_spr_data_10[2] = {
    79,0,
};

uint8_t jajp_evv_jt_spr_data_11[2] = {
    85,0,
};

uint8_t jajp_evv_jt_spr_data_12[5] = {
    39,100,90,39,0,
};

uint8_t jajp_evv_jt_spr_data_13[5] = {
    39,116,83,39,0,
};

uint8_t jajp_evv_jt_spr_data_14[5] = {
    39,116,115,39,0,
};

uint8_t jajp_evv_jt_spr_data_16[2] = {
    104,0,
};

uint8_t jajp_evv_jt_spr_data_19[2] = {
    97,0,
};

uint8_t jajp_evv_jt_spr_data_20[2] = {
    101,0,
};

uint8_t jajp_evv_jt_spr_data_21[2] = {
    105,0,
};

uint8_t jajp_evv_jt_spr_data_22[2] = {
    111,0,
};

uint8_t jajp_evv_jt_spr_data_23[2] = {
    117,0,
};

uint8_t jajp_evv_jt_spr_data_24[3] = {
    81,122,0,
};

uint8_t jajp_evv_jt_spr_data_25[3] = {
    81,116,0,
};

uint8_t jajp_evv_jt_spr_data_26[4] = {
    81,116,115,0,
};

uint8_t jajp_evv_jt_spr_data_27[4] = {
    81,115,104,0,
};

uint8_t jajp_evv_jt_spr_data_28[3] = {
    81,115,0,
};

uint8_t jajp_evv_jt_spr_data_29[3] = {
    81,112,0,
};

uint8_t jajp_evv_jt_spr_data_3[102] = {
    26,25,0,0,5,8,0,0,26,46,0,0,5,12,0,0,
    13,52,0,0,2,13,0,0,1,18,0,0,2,18,0,0,
    3,18,0,0,9,18,0,0,6,18,0,0,14,18,0,0,
    15,18,0,0,4,18,0,0,17,18,0,0,1,1,0,0,
    5,5,12,0,2,2,13,0,2,2,0,0,10,10,0,0,
    3,3,0,0,9,9,0,0,6,6,18,0,4,4,18,0,
    5,5,8,0,7,7,
};

uint8_t jajp_evv_jt_spr_data_30[4] = {
    81,112,121,0,
};

uint8_t jajp_evv_jt_spr_data_31[3] = {
    81,107,0,
};

uint8_t jajp_evv_jt_spr_data_32[4] = {
    81,107,121,0,
};

uint8_t jajp_evv_jt_spr_data_33[3] = {
    81,104,0,
};

uint8_t jajp_evv_jt_spr_data_34[3] = {
    81,103,0,
};

uint8_t jajp_evv_jt_spr_data_35[3] = {
    81,102,0,
};

uint8_t jajp_evv_jt_spr_data_36[3] = {
    81,100,0,
};

uint8_t jajp_evv_jt_spr_data_37[3] = {
    81,106,0,
};

uint8_t jajp_evv_jt_spr_data_38[4] = {
    81,99,104,0,
};

uint8_t jajp_evv_jt_spr_data_39[3] = {
    81,98,0,
};

uint8_t jajp_evv_jt_spr_data_40[3] = {
    116,115,0,
};

uint8_t jajp_evv_jt_spr_data_41[3] = {
    114,121,0,
};

uint8_t jajp_evv_jt_spr_data_42[3] = {
    112,121,0,
};

uint8_t jajp_evv_jt_spr_data_43[3] = {
    110,121,0,
};

uint8_t jajp_evv_jt_spr_data_44[3] = {
    109,121,0,
};

uint8_t jajp_evv_jt_spr_data_45[3] = {
    107,121,0,
};

uint8_t jajp_evv_jt_spr_data_46[2] = {
    106,0,
};

uint8_t jajp_evv_jt_spr_data_47[3] = {
    104,121,0,
};

uint8_t jajp_evv_jt_spr_data_48[3] = {
    103,121,0,
};

uint8_t jajp_evv_jt_spr_data_49[3] = {
    100,121,0,
};

uint8_t jajp_evv_jt_spr_data_50[3] = {
    99,104,0,
};

uint8_t jajp_evv_jt_spr_data_51[3] = {
    98,121,0,
};

uint8_t jajp_evv_jt_spr_data_52[3] = {
    115,104,0,
};

uint8_t jajp_evv_jt_spr_data_53[3] = {
    95,110,0,
};

uint8_t jajp_evv_jt_spr_data_55[3] = {
    97,58,0,
};

uint8_t jajp_evv_jt_spr_data_56[3] = {
    101,58,0,
};

uint8_t jajp_evv_jt_spr_data_57[3] = {
    105,58,0,
};

uint8_t jajp_evv_jt_spr_data_58[3] = {
    111,58,0,
};

uint8_t jajp_evv_jt_spr_data_59[3] = {
    117,58,0,
};

uint8_t jajp_evv_jt_spr_data_60[6] = {
    44,116,48,41,32,0,
};

uint8_t jajp_evv_jt_spr_data_61[3] = {
    40,112,0,
};

uint8_t jajp_evv_jt_spr_data_7[2] = {
    65,0,
};

uint8_t jajp_evv_jt_spr_data_8[2] = {
    69,0,
};

uint8_t jajp_evv_jt_spr_data_9[2] = {
    73,0,
};

uint8_t jajp_evv_u_intfac_data_3[118] = {
    48,4,3,12,2,0,0,0,18,4,24,2,28,1,72,26,
    2,73,25,5,26,4,13,2,25,5,65,0,47,1,24,4,
    4,0,0,0,37,1,21,1,18,4,0,0,38,3,24,4,
    4,0,0,0,9,11,1,1,12,16,1,21,9,17,3,3,
    25,1,21,0,8,12,16,3,24,4,4,0,51,4,25,16,
    3,24,4,4,37,3,24,4,18,4,0,0,0,0,0,1,
    0,4,128,1,128,2,130,194,130,198,130,195,130,199,130,200,
    130,201,130,196,130,197,
};

uint8_t jajp_evv_u_vars_data_3[54] = {
    128,203,0,0,128,204,0,0,129,85,129,86,128,97,128,98,
    130,236,0,0,128,97,0,0,128,97,130,237,131,3,0,0,
    131,3,130,232,131,3,131,4,130,231,0,0,0,1,2,3,
    4,5,6,7,8,9,
};

uint8_t jajp_evv_ut_anno_data_3[132] = {
    53,53,0,0,129,167,0,0,129,171,0,0,16,31,0,0,
    193,165,10,129,171,0,0,0,193,165,10,193,165,10,129,171,
    25,26,0,0,193,165,10,0,16,3,0,0,20,2,13,0,
    19,4,0,0,29,16,3,0,29,19,4,0,28,22,20,0,
    14,1,25,26,25,19,4,28,29,14,1,25,26,0,0,0,
    29,25,19,4,28,0,0,0,130,128,0,0,130,122,129,171,
    25,22,24,0,22,14,0,0,25,22,0,0,25,24,0,0,
    3,21,22,0,5,3,0,0,22,22,0,0,13,1,0,0,
    0,4,130,126,
};

uint8_t jajp_evv_ut_inton_data_3[21] = {
    129,71,0,0,0,0,0,1,0,3,0,4,1,2,3,4,
    5,6,7,8,9,
};

uint8_t jajp_evv_ut_norm_data_3[104] = {
    82,80,67,0,88,88,66,69,68,192,83,86,89,95,93,173,
    174,96,168,194,203,166,167,0,192,123,0,0,65,65,102,97,
    112,107,122,117,129,127,136,131,142,141,144,143,32,33,152,151,
    154,153,103,98,113,108,123,118,137,132,36,104,99,114,109,124,
    119,138,133,38,39,41,156,155,105,100,115,110,125,120,130,128,
    139,134,146,145,148,147,43,158,157,47,106,101,116,111,126,121,
    140,135,48,49,50,29,150,149,
};

uint8_t jajp_evv_ut_spr_bss_7[1] = {
    0,
};

uint8_t jajp_evv_ut_spr_data_10[2] = {
    96,0,
};

uint8_t jajp_evv_ut_spr_data_11[4] = {
    96,52,32,0,
};

uint8_t jajp_evv_ut_spr_data_12[4] = {
    96,51,32,0,
};

uint8_t jajp_evv_ut_spr_data_13[4] = {
    96,50,32,0,
};

uint8_t jajp_evv_ut_spr_data_14[5] = {
    96,48,48,32,0,
};

uint8_t jajp_evv_ut_spr_data_20[2] = {
    41,0,
};

uint8_t jajp_evv_ut_spr_data_21[2] = {
    44,0,
};

uint8_t jajp_evv_ut_spr_data_22[2] = {
    40,0,
};

uint8_t jajp_evv_ut_spr_data_24[2] = {
    46,0,
};

uint8_t jajp_evv_ut_spr_data_26[3] = {
    40,112,0,
};

uint8_t jajp_evv_ut_spr_data_27[2] = {
    104,0,
};

uint8_t jajp_evv_ut_spr_data_29[3] = {
    44,116,0,
};

uint8_t jajp_evv_ut_spr_data_31[2] = {
    119,0,
};

uint8_t jajp_evv_ut_spr_data_37[3] = {
    44,98,0,
};

uint8_t jajp_evv_ut_spr_data_4[54] = {
    74,0,0,0,0,3,0,6,0,3,0,6,0,7,0,0,
    0,6,0,0,0,0,0,2,0,1,0,0,0,0,128,59,
    0,0,130,218,0,1,0,2,0,6,0,0,0,0,0,2,
    128,197,128,194,0,1,
};

uint8_t jajp_evv_ut_spr_data_40[2] = {
    93,0,
};

uint8_t jajp_evv_ut_spr_data_41[3] = {
    96,91,0,
};

uint8_t jajp_evv_ut_spr_data_44[10] = {
    40,48,44,48,41,32,37,32,37,0,
};

uint8_t jajp_evv_ut_spr_data_45[2] = {
    125,0,
};

uint8_t jajp_evv_ut_spr_data_46[3] = {
    41,32,0,
};

uint8_t jajp_evv_ut_spr_data_47[4] = {
    35,40,112,0,
};

uint8_t jajp_evv_ut_spr_data_48[2] = {
    36,0,
};

uint8_t jajp_evv_ut_spr_data_49[2] = {
    123,0,
};

uint8_t jajp_evv_ut_spr_data_52[2] = {
    62,0,
};

uint8_t jajp_evv_ut_spr_data_53[3] = {
    93,32,0,
};

uint8_t jajp_evv_ut_spr_data_54[3] = {
    32,91,0,
};

uint8_t jajp_evv_ut_spr_data_55[2] = {
    60,0,
};

uint8_t jajp_evv_ut_spr_data_59[3] = {
    32,37,0,
};

uint8_t jajp_evv_ut_spr_data_6[2] = {
    32,0,
};

uint8_t jajp_evv_ut_struc_data_3[15] = {
    2,3,4,6,7,8,9,0,2,3,4,6,7,8,9,
};

uint8_t jajp_evv_ut_util_data_3[10] = {
    56,57,58,59,60,61,62,0,76,80,
};

/* Where each store is and how big, so that startup can
   copy them somewhere a value can name. src/delta/delta_low.c is
   the only reader: the machine holds addresses of these, and
   an address in the program is not one a value can hold
   unless the program was linked low, which a shared library
   cannot be. sizeof rather than a number, so that a record
   appended by tools/delta-dict.py is counted without this
   table being touched. */
const delta_store jajp_delta_const_store[] = {
    { jajp_evv_glob_bss_4, sizeof jajp_evv_glob_bss_4 },
    { jajp_evv_glob_data_3, sizeof jajp_evv_glob_data_3 },
    { jajp_evv_ja_text_data_3, sizeof jajp_evv_ja_text_data_3 },
    { jajp_evv_js_cdur_data_3, sizeof jajp_evv_js_cdur_data_3 },
    { jajp_evv_jt_phnol_data_3, sizeof jajp_evv_jt_phnol_data_3 },
    { jajp_evv_jt_spr_bss_15, sizeof jajp_evv_jt_spr_bss_15 },
    { jajp_evv_jt_spr_data_10, sizeof jajp_evv_jt_spr_data_10 },
    { jajp_evv_jt_spr_data_11, sizeof jajp_evv_jt_spr_data_11 },
    { jajp_evv_jt_spr_data_12, sizeof jajp_evv_jt_spr_data_12 },
    { jajp_evv_jt_spr_data_13, sizeof jajp_evv_jt_spr_data_13 },
    { jajp_evv_jt_spr_data_14, sizeof jajp_evv_jt_spr_data_14 },
    { jajp_evv_jt_spr_data_16, sizeof jajp_evv_jt_spr_data_16 },
    { jajp_evv_jt_spr_data_19, sizeof jajp_evv_jt_spr_data_19 },
    { jajp_evv_jt_spr_data_20, sizeof jajp_evv_jt_spr_data_20 },
    { jajp_evv_jt_spr_data_21, sizeof jajp_evv_jt_spr_data_21 },
    { jajp_evv_jt_spr_data_22, sizeof jajp_evv_jt_spr_data_22 },
    { jajp_evv_jt_spr_data_23, sizeof jajp_evv_jt_spr_data_23 },
    { jajp_evv_jt_spr_data_24, sizeof jajp_evv_jt_spr_data_24 },
    { jajp_evv_jt_spr_data_25, sizeof jajp_evv_jt_spr_data_25 },
    { jajp_evv_jt_spr_data_26, sizeof jajp_evv_jt_spr_data_26 },
    { jajp_evv_jt_spr_data_27, sizeof jajp_evv_jt_spr_data_27 },
    { jajp_evv_jt_spr_data_28, sizeof jajp_evv_jt_spr_data_28 },
    { jajp_evv_jt_spr_data_29, sizeof jajp_evv_jt_spr_data_29 },
    { jajp_evv_jt_spr_data_3, sizeof jajp_evv_jt_spr_data_3 },
    { jajp_evv_jt_spr_data_30, sizeof jajp_evv_jt_spr_data_30 },
    { jajp_evv_jt_spr_data_31, sizeof jajp_evv_jt_spr_data_31 },
    { jajp_evv_jt_spr_data_32, sizeof jajp_evv_jt_spr_data_32 },
    { jajp_evv_jt_spr_data_33, sizeof jajp_evv_jt_spr_data_33 },
    { jajp_evv_jt_spr_data_34, sizeof jajp_evv_jt_spr_data_34 },
    { jajp_evv_jt_spr_data_35, sizeof jajp_evv_jt_spr_data_35 },
    { jajp_evv_jt_spr_data_36, sizeof jajp_evv_jt_spr_data_36 },
    { jajp_evv_jt_spr_data_37, sizeof jajp_evv_jt_spr_data_37 },
    { jajp_evv_jt_spr_data_38, sizeof jajp_evv_jt_spr_data_38 },
    { jajp_evv_jt_spr_data_39, sizeof jajp_evv_jt_spr_data_39 },
    { jajp_evv_jt_spr_data_40, sizeof jajp_evv_jt_spr_data_40 },
    { jajp_evv_jt_spr_data_41, sizeof jajp_evv_jt_spr_data_41 },
    { jajp_evv_jt_spr_data_42, sizeof jajp_evv_jt_spr_data_42 },
    { jajp_evv_jt_spr_data_43, sizeof jajp_evv_jt_spr_data_43 },
    { jajp_evv_jt_spr_data_44, sizeof jajp_evv_jt_spr_data_44 },
    { jajp_evv_jt_spr_data_45, sizeof jajp_evv_jt_spr_data_45 },
    { jajp_evv_jt_spr_data_46, sizeof jajp_evv_jt_spr_data_46 },
    { jajp_evv_jt_spr_data_47, sizeof jajp_evv_jt_spr_data_47 },
    { jajp_evv_jt_spr_data_48, sizeof jajp_evv_jt_spr_data_48 },
    { jajp_evv_jt_spr_data_49, sizeof jajp_evv_jt_spr_data_49 },
    { jajp_evv_jt_spr_data_50, sizeof jajp_evv_jt_spr_data_50 },
    { jajp_evv_jt_spr_data_51, sizeof jajp_evv_jt_spr_data_51 },
    { jajp_evv_jt_spr_data_52, sizeof jajp_evv_jt_spr_data_52 },
    { jajp_evv_jt_spr_data_53, sizeof jajp_evv_jt_spr_data_53 },
    { jajp_evv_jt_spr_data_55, sizeof jajp_evv_jt_spr_data_55 },
    { jajp_evv_jt_spr_data_56, sizeof jajp_evv_jt_spr_data_56 },
    { jajp_evv_jt_spr_data_57, sizeof jajp_evv_jt_spr_data_57 },
    { jajp_evv_jt_spr_data_58, sizeof jajp_evv_jt_spr_data_58 },
    { jajp_evv_jt_spr_data_59, sizeof jajp_evv_jt_spr_data_59 },
    { jajp_evv_jt_spr_data_60, sizeof jajp_evv_jt_spr_data_60 },
    { jajp_evv_jt_spr_data_61, sizeof jajp_evv_jt_spr_data_61 },
    { jajp_evv_jt_spr_data_7, sizeof jajp_evv_jt_spr_data_7 },
    { jajp_evv_jt_spr_data_8, sizeof jajp_evv_jt_spr_data_8 },
    { jajp_evv_jt_spr_data_9, sizeof jajp_evv_jt_spr_data_9 },
    { jajp_evv_u_intfac_data_3, sizeof jajp_evv_u_intfac_data_3 },
    { jajp_evv_u_vars_data_3, sizeof jajp_evv_u_vars_data_3 },
    { jajp_evv_ut_anno_data_3, sizeof jajp_evv_ut_anno_data_3 },
    { jajp_evv_ut_inton_data_3, sizeof jajp_evv_ut_inton_data_3 },
    { jajp_evv_ut_norm_data_3, sizeof jajp_evv_ut_norm_data_3 },
    { jajp_evv_ut_spr_bss_7, sizeof jajp_evv_ut_spr_bss_7 },
    { jajp_evv_ut_spr_data_10, sizeof jajp_evv_ut_spr_data_10 },
    { jajp_evv_ut_spr_data_11, sizeof jajp_evv_ut_spr_data_11 },
    { jajp_evv_ut_spr_data_12, sizeof jajp_evv_ut_spr_data_12 },
    { jajp_evv_ut_spr_data_13, sizeof jajp_evv_ut_spr_data_13 },
    { jajp_evv_ut_spr_data_14, sizeof jajp_evv_ut_spr_data_14 },
    { jajp_evv_ut_spr_data_20, sizeof jajp_evv_ut_spr_data_20 },
    { jajp_evv_ut_spr_data_21, sizeof jajp_evv_ut_spr_data_21 },
    { jajp_evv_ut_spr_data_22, sizeof jajp_evv_ut_spr_data_22 },
    { jajp_evv_ut_spr_data_24, sizeof jajp_evv_ut_spr_data_24 },
    { jajp_evv_ut_spr_data_26, sizeof jajp_evv_ut_spr_data_26 },
    { jajp_evv_ut_spr_data_27, sizeof jajp_evv_ut_spr_data_27 },
    { jajp_evv_ut_spr_data_29, sizeof jajp_evv_ut_spr_data_29 },
    { jajp_evv_ut_spr_data_31, sizeof jajp_evv_ut_spr_data_31 },
    { jajp_evv_ut_spr_data_37, sizeof jajp_evv_ut_spr_data_37 },
    { jajp_evv_ut_spr_data_4, sizeof jajp_evv_ut_spr_data_4 },
    { jajp_evv_ut_spr_data_40, sizeof jajp_evv_ut_spr_data_40 },
    { jajp_evv_ut_spr_data_41, sizeof jajp_evv_ut_spr_data_41 },
    { jajp_evv_ut_spr_data_44, sizeof jajp_evv_ut_spr_data_44 },
    { jajp_evv_ut_spr_data_45, sizeof jajp_evv_ut_spr_data_45 },
    { jajp_evv_ut_spr_data_46, sizeof jajp_evv_ut_spr_data_46 },
    { jajp_evv_ut_spr_data_47, sizeof jajp_evv_ut_spr_data_47 },
    { jajp_evv_ut_spr_data_48, sizeof jajp_evv_ut_spr_data_48 },
    { jajp_evv_ut_spr_data_49, sizeof jajp_evv_ut_spr_data_49 },
    { jajp_evv_ut_spr_data_52, sizeof jajp_evv_ut_spr_data_52 },
    { jajp_evv_ut_spr_data_53, sizeof jajp_evv_ut_spr_data_53 },
    { jajp_evv_ut_spr_data_54, sizeof jajp_evv_ut_spr_data_54 },
    { jajp_evv_ut_spr_data_55, sizeof jajp_evv_ut_spr_data_55 },
    { jajp_evv_ut_spr_data_59, sizeof jajp_evv_ut_spr_data_59 },
    { jajp_evv_ut_spr_data_6, sizeof jajp_evv_ut_spr_data_6 },
    { jajp_evv_ut_struc_data_3, sizeof jajp_evv_ut_struc_data_3 },
    { jajp_evv_ut_util_data_3, sizeof jajp_evv_ut_util_data_3 },
    { 0, 0 },
};
