/* Generated by tools/delta-sets.py. Do not edit.

   The language's lookup sets and its dictionary's
   actions: what each one is, and what is in it. The
   contents are bytes and nothing else, so they are here
   as they were; the machine is handed a copy of the two
   tables rather than these, because it writes to them.

   The three dictionary arrays below -- act_table,
   actent_store and actent_all -- are laid down again by
   tools/delta-dict.py out of lang/enus/enus.dict, which is
   where a word is added or an entry changed. Running
   this lifter again puts IBM's own back and loses
   whatever that file said. */

#include <stdlib.h>
#include <string.h>

#include "delta.h"
#include "delta_rules_c.h"

/* What each set is: how many entries, how wide, and
   where in its blob to start. */
static const uint8_t set_table[] = {
    0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,
    2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,0,0
};

static const uint8_t act_table[] = {
    0,0,0,0,0,0,0,0,1,0,0,0,202,0,0,0,
    148,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    0,0,255,255,255,255,0,0
};

/* The sets, as they lie. */
static const uint8_t setent_store[] = {
    1,0
};

/* Where each one starts in it. */
static const uint8_t *const setent_all[] = {
    setent_store + 0,   /* xyz_setentries */
};

/* The actions, as they lie. */
static const uint8_t actent_store[] = {
    252,0,44,1,92,1,164,1,236,1,2,1,50,1,98,1,
    170,1,242,1,8,1,20,1,32,1,56,1,68,1,80,1,
    104,1,116,1,128,1,140,1,152,1,176,1,188,1,200,1,
    212,1,224,1,248,1,4,2,16,2,28,2,40,2,14,1,
    26,1,38,1,62,1,74,1,86,1,110,1,122,1,134,1,
    146,1,158,1,182,1,194,1,206,1,218,1,230,1,254,1,
    10,2,22,2,34,2,46,2,246,0,192,0,198,0,204,0,
    210,0,216,0,222,0,228,0,234,0,240,0,60,0,156,0,
    168,0,186,0,138,0,132,0,0,0,48,0,54,0,144,0,
    12,0,66,0,96,0,102,0,42,0,6,0,108,0,120,0,
    114,0,126,0,18,0,78,0,24,0,180,0,72,0,30,0,
    36,0,90,0,84,0,162,0,174,0,150,0,58,2,154,2,
    202,2,18,3,90,3,52,2,148,2,196,2,12,3,84,3,
    70,2,166,2,214,2,30,3,102,3,64,2,160,2,208,2,
    24,3,96,3,82,2,178,2,226,2,42,3,114,3,76,2,
    172,2,220,2,36,3,108,3,94,2,54,3,88,2,48,3,
    106,2,190,2,238,2,66,3,126,3,100,2,184,2,232,2,
    60,3,120,3,118,2,112,2,130,2,124,2,180,3,174,3,
    78,3,72,3,138,3,132,3,142,2,136,2,250,2,244,2,
    6,3,0,3,168,3,162,3,144,3,182,4,176,4,150,3,
    246,3,252,3,8,4,156,3,186,3,192,3,240,3,158,4,
    44,4,134,4,204,3,210,3,140,4,146,4,152,4,170,4,
    164,4,80,4,74,4,110,4,122,4,86,4,92,4,38,4,
    128,4,216,3,26,4,116,4,198,3,234,3,222,3,228,3,
    2,4,14,4,20,4,32,4,50,4,56,4,62,4,68,4,
    98,4,104,4,69,0,255,255,1,0,79,0,255,255,2,0,
    74,0,255,255,3,0,85,0,255,255,4,0,87,0,255,255,
    5,0,90,0,255,255,6,0,91,0,255,255,7,0,78,0,
    255,255,8,0,70,0,255,255,9,0,71,0,255,255,10,0,
    63,0,255,255,11,0,75,0,255,255,12,0,89,0,255,255,
    13,0,86,0,255,255,14,0,93,0,255,255,15,0,92,0,
    255,255,16,0,76,0,255,255,17,0,77,0,255,255,18,0,
    80,0,255,255,19,0,82,0,255,255,20,0,81,0,255,255,
    21,0,83,0,255,255,22,0,68,0,255,255,23,0,67,0,
    255,255,24,0,73,0,255,255,25,0,96,0,255,255,26,0,
    64,0,255,255,27,0,94,0,255,255,28,0,65,0,255,255,
    29,0,95,0,255,255,30,0,88,0,255,255,31,0,66,0,
    255,255,32,0,54,0,255,255,33,0,55,0,255,255,34,0,
    56,0,255,255,35,0,57,0,255,255,36,0,58,0,255,255,
    37,0,59,0,255,255,38,0,60,0,255,255,39,0,61,0,
    255,255,40,0,62,0,255,255,41,0,53,0,255,255,42,0,
    1,0,255,255,43,0,6,0,255,255,43,0,11,0,255,255,
    44,0,32,0,255,255,44,0,12,0,255,255,45,0,33,0,
    255,255,45,0,13,0,255,255,46,0,34,0,255,255,46,0,
    2,0,255,255,47,0,7,0,255,255,47,0,14,0,255,255,
    48,0,35,0,255,255,48,0,15,0,255,255,49,0,36,0,
    255,255,49,0,16,0,255,255,50,0,37,0,255,255,50,0,
    3,0,255,255,51,0,8,0,255,255,51,0,17,0,255,255,
    52,0,38,0,255,255,52,0,18,0,255,255,53,0,39,0,
    255,255,53,0,19,0,255,255,54,0,40,0,255,255,54,0,
    20,0,255,255,55,0,41,0,255,255,55,0,21,0,255,255,
    56,0,42,0,255,255,56,0,4,0,255,255,57,0,9,0,
    255,255,57,0,22,0,255,255,58,0,43,0,255,255,58,0,
    23,0,255,255,59,0,44,0,255,255,59,0,24,0,255,255,
    60,0,45,0,255,255,60,0,25,0,255,255,61,0,46,0,
    255,255,61,0,26,0,255,255,62,0,47,0,255,255,62,0,
    5,0,255,255,63,0,10,0,255,255,63,0,27,0,255,255,
    64,0,48,0,255,255,64,0,28,0,255,255,65,0,49,0,
    255,255,65,0,29,0,255,255,66,0,50,0,255,255,66,0,
    30,0,255,255,67,0,51,0,255,255,67,0,31,0,255,255,
    68,0,52,0,255,255,68,0,102,0,255,255,69,0,97,0,
    255,255,69,0,112,0,255,255,70,0,107,0,255,255,70,0,
    122,0,255,255,71,0,117,0,255,255,71,0,129,0,255,255,
    72,0,127,0,255,255,72,0,136,0,255,255,73,0,131,0,
    255,255,73,0,142,0,255,255,74,0,141,0,255,255,74,0,
    144,0,255,255,75,0,143,0,255,255,75,0,152,0,255,255,
    76,0,151,0,255,255,76,0,103,0,255,255,77,0,98,0,
    255,255,77,0,113,0,255,255,78,0,108,0,255,255,78,0,
    123,0,255,255,79,0,118,0,255,255,79,0,137,0,255,255,
    80,0,132,0,255,255,80,0,104,0,255,255,81,0,99,0,
    255,255,81,0,114,0,255,255,82,0,109,0,255,255,82,0,
    124,0,255,255,83,0,119,0,255,255,83,0,138,0,255,255,
    84,0,133,0,255,255,84,0,154,0,255,255,85,0,153,0,
    255,255,85,0,156,0,255,255,86,0,155,0,255,255,86,0,
    105,0,255,255,87,0,100,0,255,255,87,0,115,0,255,255,
    88,0,110,0,255,255,88,0,125,0,255,255,89,0,120,0,
    255,255,89,0,130,0,255,255,90,0,128,0,255,255,90,0,
    139,0,255,255,91,0,134,0,255,255,91,0,148,0,255,255,
    92,0,147,0,255,255,92,0,106,0,255,255,93,0,101,0,
    255,255,93,0,116,0,255,255,94,0,111,0,255,255,94,0,
    126,0,255,255,95,0,121,0,255,255,95,0,140,0,255,255,
    96,0,135,0,255,255,96,0,150,0,255,255,97,0,149,0,
    255,255,97,0,159,0,255,255,98,0,162,0,255,255,99,0,
    166,0,255,255,100,0,158,0,255,255,101,0,157,0,255,255,
    101,0,146,0,255,255,102,0,145,0,255,255,102,0,167,0,
    255,255,103,0,168,0,255,255,104,0,193,0,255,255,105,0,
    173,0,255,255,106,0,174,0,255,255,107,0,188,0,255,255,
    108,0,195,0,255,255,109,0,196,0,255,255,109,0,194,0,
    255,255,110,0,169,0,255,255,111,0,163,0,255,255,112,0,
    164,0,255,255,113,0,197,0,255,255,114,0,165,0,255,255,
    115,0,198,0,255,255,116,0,199,0,255,255,117,0,189,0,
    255,255,118,0,200,0,255,255,119,0,186,0,255,255,120,0,
    171,0,255,255,121,0,201,0,255,255,122,0,202,0,255,255,
    123,0,203,0,255,255,124,0,204,0,255,255,125,0,181,0,
    255,255,126,0,180,0,255,255,127,0,184,0,255,255,128,0,
    185,0,255,255,129,0,205,0,255,255,130,0,206,0,255,255,
    131,0,182,0,255,255,132,0,191,0,255,255,133,0,183,0,
    255,255,134,0,187,0,255,255,135,0,172,0,255,255,136,0,
    175,0,255,255,137,0,176,0,255,255,138,0,177,0,255,255,
    139,0,170,0,255,255,140,0,179,0,255,255,141,0,178,0,
    255,255,142,0,161,0,255,255,143,0,160,0,255,255,143,0
};

/* Where each one starts in it. */
static const uint8_t *const actent_all[] = {
    actent_store + 0,   /* jap_char_name_actentries */
};

/* The streams the language can open by name, and the
   dictionary it looks its words up in. */
static const char *const lfnames[] = {
    "pgmin",
    "pgmout",
    "cmdin",
    "cmdout",
    "prompt",
    "prmout",
    "wordsin",
    "cmdfile",
    "sprout",
    "consprout",
    "execfile",
    "errorout",
    "ecijajp.ddl",
};

static const char dictfile[] = "ecijajp.ddl";

/* Hand the machine what it needs of all this.

   The two tables are copied rather than handed over, because the machine
   writes to them, and it is given room for more than the language declares,
   which is what the original allocates. The stores themselves are handed
   over as they are. */
void jajp_set_dict_new(delta_state *d)
{
    delta_low_region(setent_store, sizeof setent_store);
    d->set_store = EVV_REF(delta_low_copy(setent_all, sizeof setent_all));
}

void jajp_set_dict_delete(delta_state *d)
{
    if (d != 0)
        d->set_store = EVV_REF(0);
}

void jajp_act_dict_new(delta_state *d)
{
    delta_low_region(actent_store, sizeof actent_store);
    d->act_store = EVV_REF(delta_low_copy(actent_all, sizeof actent_all));
}

void jajp_act_dict_delete(delta_state *d)
{
    if (d != 0)
        d->act_store = EVV_REF(0);
}

void jajp_link_new(delta_state *d)
{
    d->fence_room = 25;

    d->fence_chars = EVV_REF(malloc(10));
    d->fence_chars_base = d->fence_chars;
    if (d->fence_chars == 0) { delta_delete(d); return; }
    d->fence_index = EVV_REF(malloc(10));
    d->fence_index_base = d->fence_index;
    if (d->fence_index == 0) { delta_delete(d); return; }
    d->fence_marks = EVV_REF(malloc(11));
    d->fence_marks_base = d->fence_marks;
    if (d->fence_marks == 0) { delta_delete(d); return; }

    d->nstmts = 10;
    d->lang_a = 1;
    d->lang_b = 2;
    d->lfnames = EVV_REF(delta_low_copy(lfnames, sizeof lfnames));
    d->nlfnames = 13;
    d->nsets = 1;
    d->dictfile = EVV_REF(delta_low_copy(dictfile, sizeof dictfile));
    d->nactions = 1;

    d->sets = EVV_REF(malloc(20664));
    if (EVV_AT(uint8_t *, d->sets) == 0) { delta_delete(d); return; }
    memcpy(EVV_AT(uint8_t *, d->sets), set_table, sizeof set_table);

    d->act_table = EVV_REF(malloc(1160));
    if (EVV_AT(uint8_t *, d->act_table) == 0) { delta_delete(d); return; }
    memcpy(EVV_AT(uint8_t *, d->act_table), act_table, sizeof act_table);
}

void jajp_link_delete(delta_state *d)
{
    if (d == 0)
        return;
    free(EVV_AT(uint8_t *, d->fence_index_base));
    d->fence_index_base = EVV_REF(0);
    free(EVV_AT(uint8_t *, d->fence_chars_base));
    d->fence_chars_base = EVV_REF(0);
    free(EVV_AT(uint8_t *, d->fence_marks_base));
    d->fence_marks_base = EVV_REF(0);
    free(EVV_AT(uint8_t *, d->sets));
    d->sets = EVV_REF(0);
    free(EVV_AT(uint8_t *, d->act_table));
    d->act_table = EVV_REF(0);
}
