/* Generated by tools/rules/consts.py. Do not edit.

   Bytes a rule of ours names by address, out of lang/eses/rules/constants.
   The lifted ones are in delta_consts_eses.c, generated out of IBM's
   objects; these are kept apart so that running that lifter again cannot lose
   them.

   Everything here is copied into the arena at startup beside the lifted
   stores, because the machine holds addresses in thirty-two bit values and an
   address in the program is not one of those. */

#include <stdint.h>

#include "delta_lang.h"

uint8_t eses_evv_authored_data[] = {
    /* fence_03, 1 bytes at 0 */
    3,
    /* say_04, 1 bytes at 1 */
    4,
    /* say_05, 1 bytes at 2 */
    5,
    /* say_0b, 1 bytes at 3 */
    11,
    /* say_10, 1 bytes at 4 */
    16,
    /* say_16, 1 bytes at 5 */
    22,
    /* say_18, 1 bytes at 6 */
    24,
    /* say_1e, 1 bytes at 7 */
    30,
    /* say_0f, 1 bytes at 8 */
    15,
    /* say_0d, 1 bytes at 9 */
    13,
    /* lts_ll, 2 bytes at 10 */
    19,19,
    /* say_15, 1 bytes at 12 */
    21,
    /* say_1c, 1 bytes at 13 */
    28,
    /* lts_qu, 2 bytes at 14 */
    23,5,
    /* lts_e, 1 bytes at 16 */
    2,
    /* lts_6c, 1 bytes at 17 */
    108,
    /* lts_6d, 1 bytes at 18 */
    109,
    /* say_0e, 1 bytes at 19 */
    14,
    /* lts_l, 1 bytes at 20 */
    19,
    /* lts_m, 1 bytes at 21 */
    20,
    /* lts_ai, 2 bytes at 22 */
    1,3,
    /* say_211d, 2 bytes at 24 */
    33,29,
    /* lts_6b03, 2 bytes at 26 */
    107,3,
    /* say_21, 1 bytes at 28 */
    33,
    /* lts_ei, 2 bytes at 29 */
    2,3,
    /* say_201d, 2 bytes at 31 */
    32,29,
    /* lts_6c03, 2 bytes at 33 */
    108,3,
    /* say_20, 1 bytes at 35 */
    32,
    /* lts_oi, 2 bytes at 36 */
    4,3,
    /* say_221d, 2 bytes at 38 */
    34,29,
    /* say_22, 1 bytes at 40 */
    34,
    /* say_1f, 1 bytes at 41 */
    31,
    /* say_1d, 1 bytes at 42 */
    29,
    /* say_23, 1 bytes at 43 */
    35,
    /* lts_a, 1 bytes at 44 */
    1,
    /* lts_ch, 2 bytes at 45 */
    12,16,
    /* lts_gu, 2 bytes at 47 */
    15,5,
    /* say_06, 1 bytes at 49 */
    6,
    /* lts_ng, 2 bytes at 50 */
    21,15,
    /* say_17, 1 bytes at 52 */
    23,
    /* lts_ps, 2 bytes at 53 */
    22,25,
    /* lts_rr, 2 bytes at 55 */
    24,24,
    /* say_1b, 1 bytes at 57 */
    27,
    /* lts_s, 1 bytes at 58 */
    25,
    /* say_1a, 1 bytes at 59 */
    26,
    /* say_0a, 1 bytes at 60 */
    10,
};

const delta_store eses_delta_authored_store[] = {
    { eses_evv_authored_data, sizeof eses_evv_authored_data },
    { 0, 0 },
};
